# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tharun Prabhu
tagline:          "Blog"
description:      'This is my personal blog where I write about movies, technology, news and everything else that I have an opinion about'
url:              https://tharunprabhu.github.io/blog/
baseurl:          /

author:
  name:           'Tharun Prabhu'
  url:            https://github.com/tharunprabhu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
