# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tharun Prabhu
tagline:          "Blog"
description:      ''
url:              https://tharunprabhu.github.io/
baseurl:          /

author:
  name:           'Tharun Prabhu'
  url:            https://github.com/tharunprabhu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
